// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Config = require("./Config.bs.js");
var Js_math = require("rescript/lib/js/js_math.js");
var Belt_HashMapString = require("rescript/lib/js/belt_HashMapString.js");

var sqrSize = Math.imul(Config.boardSize, Config.boardSize);

var sumOfSquares = (sqrSize << 1);

var diagonalLength = Math.sqrt(sumOfSquares);

var hueIncrement = 360 / diagonalLength;

var colorCache = Belt_HashMapString.make(sqrSize);

function rainbowHSL(y, x) {
  var cacheKey = "" + y + "-" + x;
  var found = Belt_HashMapString.get(colorCache, cacheKey);
  var match;
  if (found !== undefined) {
    match = [
      found,
      true
    ];
  } else {
    var sumOfPoints = Math.imul(y, y) + Math.imul(x, x) | 0;
    var raw = Math.sqrt(sumOfPoints) * hueIncrement;
    var h = Js_math.floor(raw);
    var color = "hsl(" + h + ", 100%, 60%)";
    match = [
      color,
      false
    ];
  }
  var color$1 = match[0];
  if (!match[1]) {
    Belt_HashMapString.set(colorCache, cacheKey, color$1);
  }
  return color$1;
}

var Colors = {
  sqrSize: sqrSize,
  sumOfSquares: sumOfSquares,
  diagonalLength: diagonalLength,
  hueIncrement: hueIncrement,
  colorCache: colorCache,
  rainbowHSL: rainbowHSL
};

exports.Colors = Colors;
/* diagonalLength Not a pure module */
