// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Util = require("../lib/Util.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Config = require("../lib/Config.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var deleteProp = ((newProps, key) => delete newProps[key]);

function getOrEmpty(str) {
  if (str !== undefined) {
    return " " + str;
  } else {
    return "";
  }
}

function styles(background, shadow, tileSize, param) {
  return "\n    width: " + tileSize + ";\n    height: " + tileSize + ";\n    background: " + background + "\n    box-shadow: " + shadow + "\n    border-radius: 50%;\n    margin: 2px 1px;\n    padding: 0;\n    transition-property: \"all\";\n    transition-duration: .1s;\n    transition-timing-function: ease-in-out;\n    cursor: pointer;\n  ";
}

function make(props) {
  var className = styles(props.background, props.shadow, props.tileSize, undefined) + getOrEmpty(Caml_option.undefined_to_opt(props.className));
  var stylesObject = {
    className: className,
    ref: Caml_option.undefined_to_opt(props.innerRef)
  };
  var newProps = Object.assign({}, props, stylesObject);
  deleteProp(newProps, "tileSize");
  deleteProp(newProps, "shadow");
  deleteProp(newProps, "background");
  deleteProp(newProps, "innerRef");
  return React.createElement("div", newProps);
}

var Wrapper = {
  deleteProp: deleteProp,
  getOrEmpty: getOrEmpty,
  styles: styles,
  make: make
};

function Tile(Props) {
  var isAlive = Props.isAlive;
  var onToggle = Props.onToggle;
  var y = Props.y;
  var x = Props.x;
  var aliveColor = Util.Colors.rainbowHSL(y, x);
  var match = isAlive ? [
      aliveColor,
      "0 0 0 0 " + aliveColor
    ] : [
      "#272B30",
      ""
    ];
  var handleMouseEvent = React.useCallback((function (callback) {
          return function (e) {
            if (e.nativeEvent.which === 1) {
              return Curry._1(callback, undefined);
            }
            
          };
        }), []);
  return React.createElement(make, {
              onMouseDown: Curry._1(handleMouseEvent, onToggle),
              onMouseOver: Curry._1(handleMouseEvent, onToggle),
              tileSize: Config.tileSize,
              shadow: match[1],
              background: match[0]
            });
}

var make$1 = Tile;

exports.Wrapper = Wrapper;
exports.make = make$1;
/* Util Not a pure module */
