// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactHotToast = require("react-hot-toast");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactHotToast.Toaster, {}), React.createElement("div", {
                  className: "min-h-screen flex flex-col container mx-auto"
                }, React.createElement("header", {
                      className: "p-2 bg-indigo-200"
                    }, "Header"), React.createElement("main", {
                      className: "flex-1 bg-indigo-50 p-2"
                    }, React.createElement("div", {
                          className: "mb-20"
                        }, "Content1")), React.createElement("footer", {
                      className: "p-2 bg-indigo-200"
                    }, "Footer")));
}

var make = App;

exports.make = make;
/* react Not a pure module */
