// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactHotToast = require("react-hot-toast").default;
var ReactHotToast$1 = require("react-hot-toast");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactHotToast$1.Toaster, {}), React.createElement("div", {
                  className: "container mx-auto",
                  onClick: (function (param) {
                      ReactHotToast.success("Success!");
                      
                    })
                }, "Hello World 1"));
}

var make = App;

exports.make = make;
/* react Not a pure module */
