// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactHotToast = require("react-hot-toast").default;
var ReactHotToast$1 = require("react-hot-toast");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(ReactHotToast$1.Toaster, {}), React.createElement("div", {
                  className: "min-h-screen flex flex-col container mx-auto"
                }, React.createElement("header", {
                      className: "p-2 bg-indigo-200"
                    }, React.createElement("div", {
                          className: "flex flex-row items-stretch",
                          onClick: (function (param) {
                              ReactHotToast.success("Success!");
                              
                            })
                        }, React.createElement("div", {
                              className: "mr-4"
                            }, React.createElement("img", {
                                  className: "inline-block rounded-full ring ring-white w-12 h-12",
                                  src: "https://avatars.githubusercontent.com/u/37130869?v=4"
                                })), React.createElement("div", {
                              className: "basis-1/4 flex items-center"
                            }, React.createElement("p", {
                                  className: "text-base"
                                }, "https://github.com/Zhang-WJ")))), React.createElement("main", {
                      className: "flex-1 bg-indigo-50 p-2"
                    }, React.createElement("div", {
                          className: "mb-20"
                        }, "Content1")), React.createElement("footer", {
                      className: "p-2 bg-indigo-200"
                    }, "Footer")));
}

var make = App;

exports.make = make;
/* react Not a pure module */
