// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lifegame from "./components/Lifegame.bs.js";
import * as ReactDom from "react-dom";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

require('./index.css')
;

var randomSeed = Date.now() | 0;

var fallback = React.createElement("div", undefined, "...");

var app = React.createElement(React.Suspense, {
      children: React.createElement(Lifegame.make, {
            key: "app"
          }),
      fallback: fallback
    });

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(app, root);
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  randomSeed ,
  fallback ,
  app ,
  root$1 as root,
  
}
/*  Not a pure module */
