// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Lifegame = require("./components/Lifegame.bs.js");
var ReactDom = require("react-dom");
var Caml_option = require("rescript/lib/js/caml_option.js");

require('./index.css')
;

var randomSeed = Date.now() | 0;

var fallback = React.createElement("div", undefined, "...");

var app = React.createElement(React.Suspense, {
      children: React.createElement(Lifegame.make, {
            key: "app"
          }),
      fallback: fallback
    });

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(app, root);
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

exports.randomSeed = randomSeed;
exports.fallback = fallback;
exports.app = app;
exports.root = root$1;
/*  Not a pure module */
